CUDA_VISIBLE_DEVICES='1' python main.py \
    --output_dir ./trails/SRGAN/ \
    --summary_dir ./trails/SRGAN/log/ \
    --mode train \
    --is_training True \
    --task SRGAN \
    --batch_size 16 \
    --crop_size 24 \
    --input_dir_LR /home/share/ziyumeng/Yucheng/Data/HCP_lipid_slice/LR/ \
    --input_dir_HR /home/share/ziyumeng/Yucheng/Data/HCP_lipid_slice/HR/ \
    --perceptual_mode MSE \
    --name_queue_capacity 4096 \
    --image_queue_capacity 4096 \
    --ratio 0.001 \
    --learning_rate 0.0001 \
    --decay_step 100000 \
    --decay_rate 0.1 \
    --stair True \
    --beta 0.9 \
    --max_iter 500000 \
    --queue_thread 10 \
    --vgg_scaling 0.0061 \
    --pre_trained_model True \
    --checkpoint ./trails/SRunet/model-300000
