#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES='4' python main.py \
    --output_dir ./trails/SRunet/ \
    --summary_dir ./trails/SRunet/log/ \
    --mode train \
    --is_training True \
    --task unet \
    --batch_size 4 \
    --interpolation True \
    --crop_size 256 \
    --input_dir_LR /home/share/ziyumeng/Yucheng/Data/HCP_lipid_slice/LR/ \
    --input_dir_HR /home/share/ziyumeng/Yucheng/Data/HCP_lipid_slice/HR/ \
    --name_queue_capacity 4096 \
    --image_queue_capacity 4096 \
    --perceptual_mode MSE \
    --queue_thread 12 \
    --ratio 0.001 \
    --learning_rate 0.0001 \
    --decay_step 500000 \
    --decay_rate 0.1 \
    --stair True \
    --beta 0.9 \
    --max_iter 200000 \
    --save_freq 20000
